SET MGNLQ_TESTMODEL_REPLAY=
SET MGNLQ_TESTMODEL2_REPLAY=
SET MGNLQ_RECORD_REPLAY=
SET ABOT_MODELPATH=
SET ABOT_MONGODB=
SET ABOT_WRITE_REGRESS=

SET MGNLQ_MODEL_NO_FILECACHE=1

SET MONGO_DBURL=
SET MGNLQ_MODELPATH=


TITLE mgnql_model_env_plain
COLOR 07